// <auto-generated />
using System;
using AcademyApp.DLL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademyApp.DLL.Data.Migrations
{
    [DbContext(typeof(AcademyDbContext))]
    partial class AcademyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcademyApp.Core.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Limit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Learn to build stunning user interfaces with HTML, CSS, and JavaScript.",
                            Limit = 20,
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Master server-side programming and database management.",
                            Limit = 15,
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Become proficient in both frontend and backend technologies.",
                            Limit = 10,
                            Name = "Fullstack Development"
                        });
                });

            modelBuilder.Entity("AcademyApp.Core.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("RegularExpression", "^[a-zA-Z0-9._%+-]+@code\\.edu\\.az$");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2000, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aysel.mammadova@code.edu.az",
                            FirstName = "Aysel",
                            GroupId = 1,
                            LastName = "Mammadova"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2001, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elvin.aliyev@code.edu.az",
                            FirstName = "Elvin",
                            GroupId = 1,
                            LastName = "Aliyev"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1999, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "leyla.hasanova@code.edu.az",
                            FirstName = "Leyla",
                            GroupId = 2,
                            LastName = "Hasanova"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2002, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reshad.quliyev@code.edu.az",
                            FirstName = "Rəşad",
                            GroupId = 2,
                            LastName = "Quliyev"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2000, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nermin.ahmadova@code.edu.az",
                            FirstName = "Nərmin",
                            GroupId = 3,
                            LastName = "Əhmədova"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2001, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tural.ibrahimov@code.edu.az",
                            FirstName = "Tural",
                            GroupId = 1,
                            LastName = "İbrahimov"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1998, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gunel.mammadli@code.edu.az",
                            FirstName = "Günel",
                            GroupId = 1,
                            LastName = "Məmmədli"
                        });
                });

            modelBuilder.Entity("AcademyApp.Core.Models.Student", b =>
                {
                    b.HasOne("AcademyApp.Core.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AcademyApp.Core.Models.Group", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
